import {  Manrope, Space_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper";
import Header from "./components/Header";
import localFont from 'next/font/local'
import Footer from "./sections/Footer";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: "400",
  subsets: ["latin"]
})

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["400", "500"],
  subsets: ["latin"]
})
const schabo = localFont({
  src: "../public/SCHABO-Condensed.otf",
  variable: "--font-schabo",
  display: "swap"
})


export const metadata = {
  title: "LVI Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} ${manrope.variable} ${schabo.variable}`}>
        <Header />
       <ClientWrapper> {children}</ClientWrapper>
       <Footer />
      </body>
    </html>
  );
}
